<head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></head> <?php include 'configure.php';$title = "Privacy Policy - $home_title";$description = "Privacy Policy - $home_des"; include 'inc/header.php'; echo'<div class="maincontener"><center><div class="topnav" id="myTopnav">  <a href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/pop.html"><i class="fa fa-music" aria-hidden="true"></i> Pop</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/blues.html"><i class="fa fa-music" aria-hidden="true"></i> Blues</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/rock.html"><i class="fa fa-music" aria-hidden="true"></i> Rock</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/reggae.html"><i class="fa fa-music" aria-hidden="true"></i> Reggae</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/hiphop.html"><i class="fa fa-music" aria-hidden="true"></i> Hip-Hop</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/dmca.html"><i class="fa fa-copyright" aria-hidden="true"></i> DMCA</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/privacy.html"><i class="fa fa-eye" aria-hidden="true"></i> Privacy</a>  <a href="//'.$_SERVER['HTTP_HOST'].'/contact.html"><i class="fa fa-envelope-o" aria-hidden="true"></i> Contact</a>  <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a></div> <script> function myFunction() {    var x = document.getElementById("myTopnav");    if (x.className === "topnav") {        x.className += " responsive";    } else {        x.className = "topnav";    } } </script><br/> '; include 'ads/728.php'; echo ' <div class="item">    <center><h2>Privacy Policy</h2></center>  </div> 
<div style="text-align: left;padding-left: 20px;padding-right: 20px;">
<p>Privacy has become a major concern on the Internet. this website knows that you care how information about you is used and shared. This privacy statement describes how this website deals with your information. By visiting this website, you are accepting the practices described in this privacy statement.</p>
<br>
<h3>Personal Information</h3>
<p>this website does not require you to disclose personal information anywhere on the site. Your IP address is used to gather broad demographic information and to track your general visiting patterns. Your IP address is also used to help diagnose technical problems. this website does not sell, rent, or trade your personal information with any third parties.</p>
<br>
<h3>Cookies</h3>
<p>Cookies are small text files that are used by many sites to store or transfer information between the main site and the computer you use to access the site. These cookies are stored in a special folder in your temporary internet files directory. this website uses cookies in parts of the website. In the course of serving advertisements to this site, our third-party advertiser may place or recognize a unique "cookie" on your browser.
</p>
<br>
<h3>Advertisers</h3>
<p>We use third-party advertising companies to serve ads when you visit this website. These companies may use information about your visits to this and other websites in order to provide advertisements on this site and other sites about goods and services that may be of interest to you. The advertisements may contain cookies. The advertisements are necessary to finance the costs of keeping this site online.</p>
<br>
<h3>Contact</h3>
<p>If you have any questions about this privacy statement, the practices of this site, or your dealings with this website, you are welcome to <a href="contact.html">Contact US</a>.</p>
</div> ';
?>
<hr/><h3>Resent Search :</h3></center><div class="lr"><?php function limit_words($string, $word_limit)	{	$words = explode(" ", $string);	return implode(" ", array_splice($words, 0, $word_limit));	} $text = file_get_contents("data/history_search.txt", NULL);$text = explode('[s]:', $text);
foreach($text as & $value)	{	$value = rtrim($value);	} $out = array_slice($text, -50); $out = array_reverse($out); $out = array_unique($out); $latest = ""; foreach($out as $value) 	{	$latest.= '<a href="'; $value1 = str_replace(" ", "-", $value);	$value = strtolower($value);	$latest.= "/video/$value";	$value1 = str_replace("-", " ", $value);	$value1 = strtolower($value1);	$value1 = limit_words('' . $value1 . '', 5);	$latest.= "\"> " . ucwords($value1) . "</a> <font size='4'>|</font> ";} echo "$latest";  echo'</div>'; include 'ads/728b.php'; echo'<center><h3>Song by Country Downloader</h3><a href="/video/Lagu-indonesia-baru">Indonesian</a> | <a href="/video/New-VEVO">English</a> | <a href="/video/New-Bangla">Bangla</a> | <a href="/video/New-Hindi-Songs">Hindi</a> | <a href="/video/Latest-Malayalam">Malayalam</a> | <a href="/video/Latest-Haryanvi">Haryanvi</a> | <a href="/video/%E6%96%B0%E4%B8%AD%E5%9C%8B%E4%BA%BA">Chinese</a> |            <a href="/video/New-Arabic-Songs">Arabic</a> | <a href="/video/New-Filipino-Songs">Filipino</a> | <a href="/video/Neue-Lieder">Deutsche</a> | <a href="/video/Neues-Deutsch">German</a> | <a href="/video/New-Latin-Songs">Latin</a> | <a href="/video/Latest-Punjabi-Songs">Punjabi</a> | <a href="/video/Novas-Musicas">Portuguese</a> | <a href="/video/%E0%B9%80%E0%B8%9E%E0%B8%A5%E0%B8%87%E0%B9%83%E0%B8%AB%E0%B8%A1%E0%B9%88">Thai</a> | <a href="/video/New-Japanese">Japanese</a> | <a href="/video/New-Russian">Russian</a> | <a href="/video/Latest-Nollywood">Nigerian</a> | <a href="/video/Những-bài-hát-tiếng-Việt-mới">Vietnamese</a> | <a href="/video/Nouvelles-chansons">French</a> | <a href="/video/Latest-Persian-Songs">Persian</a> | <a href="/video/Son-Türk-Şarkılar">Turkish</a> | <a href="/video/Nuove-canzoni-italiane">Italian</a> | <a href="/video/Latest-Egyptian-Songs">Egyptian</a> | <a href="/video/New-South-Indian-Movie">South Indian Movie</a> | <a href="/video/New-South-Indian">South Indian Songs</a><br/><br/></center><br>'; echo'</div>'; include 'inc/foot.php'; ?>